version: "3.7"

services:
  postgres:
    env_file:
      - ./envs/dev/postgres.env
  django:
    build:
      context: ./django
      args:
        MODE: development
    env_file:
      - ./envs/dev/postgres.env
      - ./envs/dev/django.env
    volumes:
      - ./django/:/code/
    ports:
      - 0.0.0.0:8000:8000
    environment:
      MODE: development
      LOGS_ROOT: /code/logs/development
  frontend:
    build:
      context: ./borghetti_frontend
      args:
        MODE: development
    ports:
      - 0.0.0.0:80:80
