version: "3.7"

services:
  postgres:
    image: postgres:12
    container_name: borghetti_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
  django:
    container_name: borghetti_django
    working_dir: /code
    command: ["./docker/wait_db.sh", "./docker/start.sh"]
    restart: unless-stopped
    depends_on:
      - postgres
  frontend:
    container_name: borghetti_frontend
    working_dir: /borghetti_frontend
    restart: unless-stopped
    depends_on:
      - django



volumes:
  postgres_data:
