version: "3.7"

services:
  postgres:
    env_file:
      - ./envs/dev/postgres.env
  django:
    build:
      context: ./django
      args:
        MODE: production
    env_file:
      - ./envs/dev/postgres.env
      - ./envs/dev/django.env
    volumes:
      - ./django/:/code/
    ports:
      - 0.0.0.0:8000:8000
    environment:
      MODE: production
      LOGS_ROOT: /var/log/django
  frontend:
    build:
      context: ./borghetti_frontend
      args:
        MODE: production
    ports:
      - 0.0.0.0:8080:8080
    environment:
      VUE_APP_API_URL: https://api.borghetti.gahlert.me
