# Generated by Django 4.2.2 on 2023-06-20 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('demands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.product', verbose_name='Produto'),
        ),
    ]
