# Generated by Django 4.2.2 on 2023-06-28 02:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0003_alter_demandproduct_demand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='demand_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data da Demanda'),
        ),
    ]
