# Generated by Django 4.2.2 on 2023-06-28 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0004_demand_demand_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='demand_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Data da Demanda'),
        ),
    ]
