# Generated by Django 4.2.2 on 2023-07-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0005_alter_demand_demand_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
    ]
